# Generated by Django 5.1.3 on 2024-12-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='netchange',
        ),
        migrations.AddField(
            model_name='stock',
            name='marketCap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='url',
            field=models.URLField(default='https://example.com/default'),
        ),
    ]
